# @package _global_

train:
  num_workers: 4
  batch_size: 64
  num_epoch: 10000
  optimizer:
    mode: 'adam'
    adam:
      lr: 0.001
      betas:
        - 0.9
        - 0.999
test:
  num_workers: 4
  batch_size: 64