# @package _global_

gen_dataset:
  _target_: dataloader.dataloader.Dataset_
  cfg: ~ # set to None for now, instantiate when during running
  mode:
    _target_: dataloader.dataloader.DataloaderMode
    value: 1 # 1 for Train status, 2 for Test status for now, it will be updated during running so usually not to care this field

data:
  train_dir: 'dataset/meta/train'
  test_dir: 'dataset/meta/test'
  file_format: '*.file_extension'
  use_background_generator: true
  divide_dataset_per_gpu: false