# @package _global_

name: 'template'
working_dir: ${work_dir}
device: 'cpu'
random_seed: 1111

dist:
  master_addr: 'localhost'
  master_port: '12355'
  mode: 'nccl'
  gpus: 0 # 0 for not using dist, -1 for using all gpus
  timeout: 30 # seconds for timeout. In nccl mode, set ~ for not using timeout
log:
  use_tensorboard: false
  use_wandb: false
  wandb_init_conf:
    name: ${name}
    entity: ethan-predator
    project: ${name}
  summary_interval: 1 # interval of step
  chkpt_interval: 10 # interval of epoch
  chkpt_dir: 'chkpt'
load:
  wandb_load_path: ~
  network_chkpt_path: ~
  strict_load: false
  resume_state_path: ~
