# @package _global_

defaults:
  - _self_
  - model: default.yaml
  - datamodule: default.yaml
  - general: default.yaml
  - override hydra/job_logging: custom
  - override hydra/hydra_logging: colorlog

work_dir: ${hydra:runtime.cwd}

hydra:
  run:
    dir: ${work_dir}/outputs/${name}-${now:%Y-%m-%d_%H-%M-%S}